import { describe, it, expect } from "vitest";
import { populateTemplate } from "../src/template-engine.js";
import type { ReportSections } from "../src/types.js";

// ---------------------------------------------------------------------------
// Helpers — fixtures
// ---------------------------------------------------------------------------

/** Minimal ReportSections with only scalar fields populated. */
function makeMinimalSections(overrides: Partial<ReportSections> = {}): ReportSections {
  return {
    teamName: "Alpha Team",
    clientName: "Contoso",
    startDate: "2026-02-01",
    endDate: "2026-02-28",
    preparedBy: "Arjun",
    submissionDate: "2026-03-01",
    executiveSummary: "Things went well.",
    breakthroughs: ["Breakthrough A"],
    milestones: ["Milestone A"],
    progressTable: [],
    s360Completed: [],
    s360InProgress: [],
    releasesUpdate: "",
    icmMetrics: {
      totalResolved: 0,
      sev1: 0,
      sev2: 0,
      sev3: 0,
      hotfixes: 0,
      notes: "",
    },
    monitoringUpdate: "",
    supportUpdate: "",
    challenges: [],
    mitigations: [],
    upcomingTasks: [],
    clientActions: [],
    dataSource: "ADO",
    generatedTimestamp: "2026-03-01T12:00:00Z",
    generatedBy: "psr-agent",
    version: "0.1.0",
    ...overrides,
  };
}

const SAMPLE_TEMPLATE = `# Report: {{Team_Name}}
**Client:** {{Client_Name}}
**Period:** {{Start_Date}} - {{End_Date}}
**Prepared By:** {{Prepared_By}}
**Submission:** {{Submission_Date}}

## Executive Summary
{{Executive_Summary_Text}}

### Breakthroughs
- {{Breakthrough_1}}
- {{Breakthrough_2}}
- {{Breakthrough_3}}

### Milestones
- {{Milestone_1}}
- {{Milestone_2}}

## Progress
| Area | Status | Description | Expected |
|------|--------|-------------|----------|
| {{Project_1}} | {{Status}} | {{Description}} | {{Date}} |
| {{Project_2}} | {{Status}} | {{Description}} | {{Date}} |

## Releases
- {{Release_1}}
- {{Release_2}}

## Challenges
- {{Challenge_1}}
- {{Challenge_2}}

## Automation
- **Generated By:** {{Automation_Workflow_Name}}
`;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("populateTemplate", () => {
  it("replaces simple scalar {{placeholder}} tokens", () => {
    const sections = makeMinimalSections();
    const result = populateTemplate(SAMPLE_TEMPLATE, sections);
    expect(result).toContain("Alpha Team");
    expect(result).toContain("Contoso");
    expect(result).toContain("2026-02-01");
    expect(result).toContain("Arjun");
  });

  it("expands list placeholders when data has more items than template slots", () => {
    const sections = makeMinimalSections({
      breakthroughs: ["BT-A", "BT-B", "BT-C", "BT-D", "BT-E"],
    });
    const result = populateTemplate(SAMPLE_TEMPLATE, sections);
    // Template has 3 breakthrough slots; all 5 should appear
    expect(result).toContain("BT-A");
    expect(result).toContain("BT-D");
    expect(result).toContain("BT-E");
  });

  it("contracts list placeholders when data has fewer items than template slots", () => {
    const sections = makeMinimalSections({
      breakthroughs: ["Only one"],
    });
    const result = populateTemplate(SAMPLE_TEMPLATE, sections);
    expect(result).toContain("Only one");
    // The two unused Breakthrough slots should NOT remain as raw placeholders
    expect(result).not.toContain("{{Breakthrough_2}}");
    expect(result).not.toContain("{{Breakthrough_3}}");
  });

  it("expands table rows from progressTable array", () => {
    const rows = [
      {
        area: "Auth",
        status: "Done",
        description: "Shipped OAuth",
        expectedCompletion: "2026-02-10",
      },
      {
        area: "Search",
        status: "In Progress",
        description: "Indexing",
        expectedCompletion: "2026-03-01",
      },
      {
        area: "Billing",
        status: "New",
        description: "Design phase",
        expectedCompletion: "2026-04-01",
      },
    ];
    const sections = makeMinimalSections({ progressTable: rows });
    const result = populateTemplate(SAMPLE_TEMPLATE, sections);
    expect(result).toContain("Auth");
    expect(result).toContain("Billing");
    // Third row added beyond the 2 template slots
    expect(result).toContain("Design phase");
  });

  it("cleans up any remaining {{...}} placeholders", () => {
    const sections = makeMinimalSections();
    const result = populateTemplate(SAMPLE_TEMPLATE, sections);
    // No raw placeholder syntax should remain
    const leftoverPlaceholders = result.match(/\{\{[^}]+\}\}/g) ?? [];
    expect(leftoverPlaceholders).toHaveLength(0);
  });

  it("replaces Localization section with Releases section", () => {
    const sections = makeMinimalSections({
      releasesUpdate: "",
    });
    const result = populateTemplate(SAMPLE_TEMPLATE, sections);
    expect(result).toContain("Releases");
  });

  it("handles completely empty lists without crashing", () => {
    const sections = makeMinimalSections({
      breakthroughs: [],
      milestones: [],
      challenges: [],
      mitigations: [],
      clientActions: [],
      s360Completed: [],
      s360InProgress: [],
      progressTable: [],
      upcomingTasks: [],
    });
    // Should not throw
    const result = populateTemplate(SAMPLE_TEMPLATE, sections);
    expect(result).toBeDefined();
    // No leftover placeholders
    const leftover = result.match(/\{\{[^}]+\}\}/g) ?? [];
    expect(leftover).toHaveLength(0);
  });
});
